apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
  labels:
    app: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: authserver
  template:
    metadata:
      labels:
        name: authserver
    spec:
      containers:
        - name: authserver
          image: gio54321/authserver
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: authserver
spec:
  type: ClusterIP
  selector:
    name: authserver
  ports:
    - port: 80
      targetPort: 8080
