apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo2
  labels:
    app: echo2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: echo2
  template:
    metadata:
      labels:
        name: echo2
    spec:
      containers:
        - name: echo2
          image: gio54321/echo
          env:
            - name: ECHO_NAME
              value: echo2
            - name: AUTH_ENDPOINT
              value: http://authserver
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: echo2
spec:
  type: ClusterIP
  selector:
    name: echo2
  ports:
    - port: 80
      targetPort: 8080
